defaults :
  - modulus_default
  - arch: fully_connected  #fourier_net
  - optimizer: adam
  - scheduler: tf_exponential_lr
  - loss: sum
  - _self_

jit: False
scheduler:
  decay_rate: 0.5 #0.95  #0.5
  decay_steps: 1000

loss:
##    weights: {'u':1e-2, 'v':1e-2, 'residual_obstacle_above':1e2, 'residual_u': 1e-3, 'residual_obstacle_below':1e2, 'Poisson_2D':1e-6, 'residual_v':1e-3}
    weights: {'u':1, 'v':1, 'residual_u': 1e-1, 'Poisson_2D':1e-2, 'residual_v':1}

arch:
    fully_connected:
        layer_size: 512
        nr_layers: 2

#arch:
#  fourier_net:
#    layer_size: 512
#    nr_layers: 6

cuda_graphs: False
debug: False
summary_histograms: True

optimizer:
  lr: 5e-3  #0.001

training:
  rec_validation_freq : 50
  rec_inference_freq: 50
  rec_monitor_freq: 50
  rec_constraint_freq: 50
  max_steps : 5000
  amp: True
  amp_dtype: float32
  save_network_freq: 50
  print_stats_freq: 2
  summary_freq: 2

batch_size:
  TopWall: 600
  BottomWall: 600
  LeftWall: 600
  RightWall: 600
  Interior: 4320  #4320 #43200
  wake1_above: 100
  wake2_above: 100
  wake3_above: 100
  wake1_below: 100
  wake2_below: 100
  wake3_below: 100
  obstacle_above: 100  # This value used for calculation of points in other domains (Top, Left, ...).
  obstacle_below: 100
  Inference_int_pts: 4320

run_mode: 'train'
#run_mode: 'eval'

custom:
  obstacle_length: 0.10  # flat plate length
  unscaled_domain_height: 6
  unscaled_domain_width: 6
  dx : 0.0015  # hardcoded, please follow below lines
  dy : 0.0015  # hardcoded, please follow below lines
  # dx: 0.015 * cfg.custom.obstacle_length   # Is the distance between the main point and the constructed points across the x-axis.
  # dy: 0.015 * cfg.custom.obstacle_length  # Is the distance between the main point and the constructed point across the y-axis.
  batch_size_temp: 7     # used to calculate alpha
  neigh_point_kd_tree: 7     # number of neighbours from a point in KD-tree
  band_range_y_belt: [-0.015, 0.015]  # This is the range of y values of the belt.
  band_range_y: [-0.06, 0.06]  # This is the range of y values of the band.
  x_range_sub_pc: 0.3  # sub point cloud x range
  y_range_sub_pc: 0.6    # sub-point cloud y range
  free_stream_velocity: 10  # Mach = 0.3
  AoA: 10  # Angle of attack
